### ISSUE TITLE
Add Functionality To Print Buttons

### ISSUE THREAD

**Issue by MattMoradi** [Brett-Tech-Networking/Moradi-Notepad#11]
When the user currently clicks on Print (Crtl+P) or Print Preview (NO-KEYBINDING-PROVIDED), nothing happens. We should add print support to the notepad by using the print features from the Windows API using the .NET Framework. That way users can actually use the Print buttons on the File menu.

**Comment by hudson1740** [comment]
IT HAD PRINT SUPPORT IN FILE>print is that not working or the toolbar?

**Comment by hudson1740** [comment]
are you currently working on any patched? i can go in and fix it now if not?
