### ISSUE TITLE
Add Save Option To File Menu

### ISSUE THREAD

**Issue by MattMoradi** [Brett-Tech-Networking/Moradi-Notepad#13]
A save option would be very useful for allowing users to save their work to an existing file without having to manually override an existing file with the current Save-As option.

**Comment by hudson1740** [comment]
i have added a save option witch allows the user to save to existing file without manual override

**Comment by MattMoradi** [comment]
I wouldn't necessarily close this yet. We still need to change it so that if the user clicks save when there are no changes to be saved, it automatically redirects to the "Save As" option, allowing them to save it for the first time. That'd be better than prompting the user saying there are no changes to be saved or no existing saves.

**Comment by hudson1740** [comment]
dont see how we can when there is always text in the text box "Start Typing Here . . ."

**Comment by MattMoradi** [comment]
We'll probably have to add a statement to ignore that. For now though, we could just redirect to the "Save-As" function and not worry about the "Start Typing Here..."

**Comment by hudson1740** [comment]
This issue to the best of my knowledge is now fixed i re programmed the save button with a try catch 
to try to save the file to an existing save location first if one does not exist it will auto redirect to save as to save for the first time.
