### ISSUE TITLE
Remove "Start Typing Here" On All Themes

### ISSUE THREAD

**Issue by MattMoradi** [Brett-Tech-Networking/Moradi-Notepad#14]
Apparently the removal of the "Start Typing Here" message on mouse click is only functional on the default notepad theme. So if the user changes themes before they start typing, the "Start Typing Here" message will not be removed on mouse click and they shall have to remove it manually. We should add this feature to all themes so that if the user changes the theme prior to clicking in the text field, they can still click to remove the text.

**Comment by MattMoradi** [comment]
Wait on this issue for me to make my next commit tomorrow before fixing.

**Comment by hudson1740** [comment]
Ok

**Comment by hudson1740** [comment]
this issue has been fixed
