### ISSUE TITLE
Allow User To Start Typing On Program Launch

### ISSUE THREAD

**Issue by MattMoradi** [Brett-Tech-Networking/Moradi-Notepad#15]
In most notepad applications, the user has the ability to start typing as soon as the notepad window pops on screen, without having to click in the text field. This is a feature that should be added so that when the user launches the notepad, they can instantly start typing and the "Start Typing Here" text will automatically disappear without requiring the user to click in the text field with their mouse. This is typically a standard notepad feature and would be much more convenient than having to click in the text field each time in order to start typing. Typically in a text based console application, you would reference a .NET class-lib in order to perform this, such as Console.ReadKey(); I would imagine there are similar functions in the .NET Framework that would be compatible with the System.Windows.Forms libraries that could be used.

**Comment by hudson1740** [comment]
regardless the user will have to click to remove "start typing here . . .

**Comment by MattMoradi** [comment]
Perhaps we should remove the "Start Typing Here" on keypress as well.

**Comment by hudson1740** [comment]
dont think its necessary if you want to release it in an update you can but im only working on bold italic underline until its fixed

**Comment by MattMoradi** [comment]
We're going to have to speak about the critical status of this issue. But it depends on the standpoint of functionality or style. :D

**Comment by MattMoradi** [comment]
For now though, yes we should focus on the **Bold**/_Italic_/Underscore issue. Perhaps this "Start Typing" issue will be released in a later build. ;)

**Comment by hudson1740** [comment]
Fixed for next update
