### ISSUE TITLE
Add Save Prompt On Program Exit

### ISSUE THREAD

**Issue by MattMoradi** [Brett-Tech-Networking/Moradi-Notepad#16]
Although I was successfully able to add the save prompt to the exit feature on the file menu, I was unable to do so on the X associated with the Ubuntu Windows Forms theme. I couldn't find the method which contained the code for the Ubuntu.dll buttons. If this code is inaccessible due to it being packaged inside the .dll, perhaps we should implement the save code into the program's shutdown sequence, such as Application.Exit();

**Comment by hudson1740** [comment]
i have an idea for that i will be working on that after we find solution to bold italic underline

**Comment by MattMoradi** [comment]
This will also solve the minor irritation where the window closes too quickly.

**Comment by MattMoradi** [comment]
Fixed this by adding the Save Prompt code to Form1_FormClosing_1 method and removing it anywhere else that kills the application. This way the Save code is only called once on program exit versus in multiple areas in the class.
