### ISSUE TITLE
Deselect of Bold, Italic, Underline, Strikethrough

### ISSUE THREAD

**Issue by MattMoradi** [Brett-Tech-Networking/Moradi-Notepad#18]
If a user enables one of these features by clicking on it, but then attempts to disable it by clicking on it again, the feature is still enabled. Currently the only one of these features that has the ability to be unclicked is the **BOLD** option. Add the ability for the user to be able to click on any of these features after they've been clicked in order to disable them so the user can return back to plane old "regular text".

**Comment by hudson1740** [comment]
can now deselect each individual item Bold, Italic, Underline, Strikeout. However Still Cannot Select/Deselect all 3 continuously
