### ISSUE TITLE
Deformats When Doing Search For Words

### ISSUE THREAD

**Issue by hudson1740** [Brett-Tech-Networking/Moradi-Notepad#20]
When searching for words with  the new find option it un formats any font,

- deletes color

- resizes
etc...

**Comment by MattMoradi** [comment]
It also can't find text that has custom fonts.

**Comment by hudson1740** [comment]
Search for Text Deformat issue fixed!

A new set of code has been implemented that will no longer deformat search results, it will search, highlight, & output the result count.
