### ISSUE TITLE
Unhandled Exception: About Object

### ISSUE THREAD

**Issue by MattMoradi** [Brett-Tech-Networking/Moradi-Notepad#23]
- Cannot access a disposed object.
- Object name: 'About'

Whenever the 'About' (F1) option is selected from the Help menu, closed, and then reselected, the following unhandled exception occurs. Perhaps the object is being disposed from memory for some reason or maybe we just need to add exception handling. 

<img width="330" alt="unhandled exception" src="https://user-images.githubusercontent.com/14935352/35889719-ac64a224-0b51-11e8-990a-ec8ada91057b.PNG">

**Comment by hudson1740** [comment]
attempted to correct with try catch statement ,,, **failed**

**Comment by MattMoradi** [comment]
This actually occurs for both items on the Help menu, inducing the "Credits" object.

**Comment by hudson1740** [comment]
seems like it only occurs when doing a show another form

**Comment by hudson1740** [comment]
issue has been fixed
