### ISSUE TITLE
Unhanded Exception When Cancelling Save

### ISSUE THREAD

**Issue by tigeran2411** [Brett-Tech-Networking/Moradi-Notepad#26]
Whenever I click yes to the save prompt and then cancel it, this unhandled exception is thrown;
![error](https://user-images.githubusercontent.com/32184416/36059977-4bd51632-0df4-11e8-9639-e3c38a671745.PNG)

**Comment by hudson1740** [comment]
Fixed with message box for catch, for the moment until save option is completely fixed,, please reopen if you still get the "unhandled exception"

**Comment by MattMoradi** [comment]
Sadly this doesn't actually handle the exception. It just shows the message box. No worries though. I'll "handle" this one.

**Comment by MattMoradi** [comment]
It's been "handled."
