### ISSUE TITLE
Text Format Bar Covers Text

### ISSUE THREAD

**Issue by MattMoradi** [Brett-Tech-Networking/Moradi-Notepad#27]
After enabling the numbered lines option, the text formatting/centering bar covers up the first couple lines in the corner of the document as shown here:
<img width="224" alt="qality_writin" src="https://user-images.githubusercontent.com/14935352/36060132-bb77f48e-0df7-11e8-9ee4-9d4ab513c25d.PNG">

**Comment by hudson1740** [comment]
fixed
