### ISSUE TITLE
Multi-Color Text With Color Wheel

### ISSUE THREAD

**Issue by tigeran2411** [Brett-Tech-Networking/Moradi-Notepad#29]
Well you see, I was tryna make my essay look like the American flag (red white and blue). But every time I selected the color wheel option it deselected the text and changed the entire essay to make it look more like the Japanese flag without the circle. Please fix this so we can make Moradi Notepad great again.

**Comment by hudson1740** [comment]
already looking into it :)

**Comment by hudson1740** [comment]
fixed
