### ISSUE TITLE
Revoke Ability To FullScreen About Page

### ISSUE THREAD

**Issue by MattMoradi** [Brett-Tech-Networking/Moradi-Notepad#3]
Since formatting optimizations have not been added to the About page for full screen mode, we should remove the full screen option from the About Form. It is not and will never be necessary.
![full_screen_about](https://user-images.githubusercontent.com/14935352/28497330-9458e366-6f39-11e7-8199-3071caeb2f47.PNG)

**Comment by hudson1740** [comment]
I have removed the maximized option from the new upload as well as added a few things

**Comment by MattMoradi** [comment]
Have the changes been committed???

**Comment by MattMoradi** [comment]
Very good sir. Nice work. Impressive. :D

**Comment by MattMoradi** [comment]
The Ubuntu theme was removed from the About Form, but that is ok.

**Comment by hudson1740** [comment]
yes the theme does not support a removal of the buttons specificly
