### ISSUE TITLE
Font Sizing With Custom Fonts

### ISSUE THREAD

**Issue by tigeran2411** [Brett-Tech-Networking/Moradi-Notepad#30]
Well, I was tryna make my essay in a Georgia font because I'm not for anything that isn't in the USA. So you know I selected my essay and changed it to an authentic Georgia font and WOW! My essay shrunk before my eyes! So my natural reaction was to make the font bigger again. And when I did it reversed back to some commy font it might have well been Putin's essay. Please fix so I can have my custom American fonts as big as my diesel truck. Thank you!

**Comment by hudson1740** [comment]
:rofl: On it

**Comment by hudson1740** [comment]
NOTE TO SELF: Issue is withing the A+ A- increase decrease size (has its preset font causing it to collide with new set fonts)

**Comment by hudson1740** [comment]
A Complete rework of font style & font size drop down selectors have been done you can now have your Georgia Font In what ever size you wish without it shrinking before your eyes!!!!
