### ISSUE TITLE
Moradi Notepad Helper Not Dancing

### ISSUE THREAD

**Issue by tigeran2411** [Brett-Tech-Networking/Moradi-Notepad#36]
So you see I have always since missed Clippy the greatest helper. So I tried to recreate this great thing and I did and his name is Moradi notepad helper. And I noticed switching his head between italic and non-italic creates the illusion he is dancing. And I have an issue with the effort it takes because this is America and I don't want to have to use any effort at all. I believe Moradi notepad should offer auto dancing for my little helper. and add disco music maybe? Thank You! I just want to make Clippy the helper great again.
![moradinotepad helper](https://user-images.githubusercontent.com/32184416/36524705-d744a7d0-175b-11e8-80f4-c742f04a8ec6.PNG)

**Comment by MattMoradi** [comment]
Perhaps Clippy may be making a comeback.
Your friendly neighborhood paperclip...

**Comment by hudson1740** [comment]
turning the dancing guy you have created would be an awesome feature however to make it into a gif and dance would be difficult, I have implemented a dancing pencil that will soon give different hints in intervals of time check it out in the latest pushes
