### ISSUE TITLE
Add Grey-Out To Used Buttons

### ISSUE THREAD

**Issue by MattMoradi** [Brett-Tech-Networking/Moradi-Notepad#39]
It'd be nice if after the user has undone their changes to the point of which they can be undone no more that the button would grey out and become unclickable until there are more changes to undo. The same could be said about the Lock, Unlock, and Redo buttons, graying them out if they have already been clicked or can no longer be clicked. <img width="80" alt="toolstrip" src="https://user-images.githubusercontent.com/14935352/36620474-1508c540-18a8-11e8-932d-b5d528f4d218.PNG">

**Comment by hudson1740** [comment]
lock/unlock done

**Comment by hudson1740** [comment]
number line hide/unhide done

**Comment by hudson1740** [comment]
edit > copy
edit > select all 

done

**Comment by MattMoradi** [comment]
Perhaps the Unlock button should be greyed out by default on application start.

**Comment by hudson1740** [comment]
No not lock only unlock

**Comment by hudson1740** [comment]
fixed
