### ISSUE TITLE
Add Full Screen Capability

### ISSUE THREAD

**Issue by MattMoradi** [Brett-Tech-Networking/Moradi-Notepad#4]
Add optimizations to the notepad for full screen compatibility. This is a good feature to have on a notepad and we should be able to have this implemented soon. Until then, we may want to consider disabling the full screen button on the form until full screen optimizations are added. 
![full_screen_capability](https://user-images.githubusercontent.com/14935352/28497382-8f2c87b6-6f3a-11e7-9e25-509ebc42a1f9.PNG)

**Comment by hudson1740** [comment]
disabled full screen mode

**Comment by MattMoradi** [comment]
Sounds good. This will be a temporary fix for the first patch until we can make optimizations for it to run properly in full screen mode.

**Comment by MattMoradi** [comment]
I doubt the Ubuntu Form theme will allow you to disable the button completely though. :(

**Comment by hudson1740** [comment]
i was able to disable it completely for now ! you can see that in the last commit last night

**Comment by hudson1740** [comment]
Full Screen Capability Is Now Available This Was Fixed By Adjusting Anchors.

**Comment by MattMoradi** [comment]
Full Screen Capability Still Has Some Flaws
![fullscreenbr8k](https://user-images.githubusercontent.com/14935352/43689359-10c82012-98ae-11e8-8c66-2c48e1e8e7e8.PNG)

**Comment by hudson1740** [comment]
this issue has been fixed for next push
