### ISSUE TITLE
Release Build Failure Problem

### ISSUE THREAD

**Issue by MattMoradi** [Brett-Tech-Networking/Moradi-Notepad#40]
For some reason the Debug compiles fine, yet the Release compilation throws a bunch of compiler errors regarding Fader and Ubuntu DLL Themes. Errors seem to be all of the same type and include:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'Ubuntu_Theme' could not be found (are you missing a using directive or an assembly reference?)	Moradi Notepad	C:\Users\Mat\Source\Repos\Moradi-Notepad\Moradi Notepad\Form1.Designer.cs	1751	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'Fader_Theme' could not be found (are you missing a using directive or an assembly reference?)	Moradi Notepad	C:\Users\Mat\Source\Repos\Moradi-Notepad\Moradi Notepad\Credits.Designer.cs	200	Active

![errorz](https://user-images.githubusercontent.com/14935352/36626412-326b08f0-192a-11e8-801b-41232375cc1d.PNG)

**Comment by hudson1740** [comment]
i have fixed this issue

By adding reference location folder back to where theme dll's are located
