### ISSUE TITLE
Add Voice-To-Text Indicator To Status Bar

### ISSUE THREAD

**Issue by MattMoradi** [Brett-Tech-Networking/Moradi-Notepad#43]
On the status bar in the bottom left corner, there should be a status for when voice-to-text is enabled. Perhaps even a "processing" status would be nice to indicate to the user that their words are being processed after they've spoken. It would also be nice to have a mic indicator light that illuminates whenever the user is speaking, or when there is mic input. ![status_bar](https://user-images.githubusercontent.com/14935352/37126896-0afb6464-226b-11e8-9c19-282ee0870515.PNG)

**Comment by hudson1740** [comment]
Added status bar update indicating that the mic has been enabled/disabled

**Comment by hudson1740** [comment]
added flashing mini mic alerting users mic is in use

**Comment by MattMoradi** [comment]
Looks good. I still think it'd be cool if we had one on the status bar that blinks or flashes whenever there is microphone input. We'll have to look into it.
