### ISSUE TITLE
Save Doesn't Work For TXT Format

### ISSUE THREAD

**Issue by MattMoradi** [Brett-Tech-Networking/Moradi-Notepad#45]
When using the "Save" option to save to an existing .txt file, the saved document contains the following output surrounding the text I typed, in this case being _fasafsfs_:

{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Arial Rounded MT Bold;}}
{\colortbl ;\red0\green255\blue0;}
\viewkind4\uc1\pard\cf1\f0\fs20 fasafsfs\par
}

**Comment by hudson1740** [comment]
I do not understand the issue I have tested the save button and the current code will save what ever format is being used

**Comment by hudson1740** [comment]
This happens when opining saved files from Moradi Notepad to other editors

**Comment by hudson1740** [comment]
This issue has a temporary fix we implemented a new menu that will allow you to choose .txt or .rtf with different menu options. A more direct fix will be implemented in the future.
![image](https://user-images.githubusercontent.com/29939215/97066020-aa78b780-157f-11eb-8d1c-c103b0715aa1.png)

**Comment by hudson1740** [comment]
This issue is temporary corrected I will move this to the projects list but no longer see this as an "issue" as a future improvement in "projects" section.
