### ISSUE TITLE
Form Closing, Application Runs In Background

### ISSUE THREAD

**Issue by hudson1740** [Brett-Tech-Networking/Moradi-Notepad#47]
Whenever I close the application it ends up continuing to run in the background( which is now fixed with Application.exit(); , when I fix the issue in form1 closing by adding line **Application.Exit();** after **ss.close** it then prompts twice for save

**Comment by MattMoradi** [comment]
Anytime Application.Exit() is called, the save prompt is also referenced. We just have to ensure it terminates the environment when a mic isn't detected, as this issue is actually dependent on if your mic is detected or not, oddly enough. Fear not though, for it has been resolved.
