### ISSUE TITLE
Disable Highlighter Option

### ISSUE THREAD

**Issue by MattMoradi** [Brett-Tech-Networking/Moradi-Notepad#49]
Currently after selecting a color on the highlighter menu, it cannot be turned off; you can only select another color. Perhaps we should add a _None_ option to the dropdown menu. We simply need a way to revert the state back to before a color was selected.

**Comment by hudson1740** [comment]
I've added A "Clear Highlight" Option which will return the highlighted text to its normal state prior to using highlighter
