### ISSUE TITLE
Add Pop-Up Info To Tools Menu Bar

### ISSUE THREAD

**Issue by MattMoradi** [Brett-Tech-Networking/Moradi-Notepad#5]
When the user mouses over the various buttons on the menu bar, add text to the pop-ups so that when they hover over a button with their mouse, the name of the tool pops up so they can see what each button on the bar does. Text already shows up when you mouse over the buttons, just change it from the defaults so that it shows something that is actually meaningful to the user.

**Comment by hudson1740** [comment]
done

**Comment by hudson1740** [comment]
I hace added hover details to toolbar buttons in the last upload

**Comment by MattMoradi** [comment]
Looks gr8 man. Nice work. I accidently reopened. My bad. :D
