### ISSUE TITLE
Remove Empty On-Click Methods

### ISSUE THREAD

**Issue by MattMoradi** [Brett-Tech-Networking/Moradi-Notepad#53]
There are a ton of empty button click methods with names like _button_click_ that contain no code. These are generated when simply double clicking a component in the visual form editor and were probably clicked by accident. 

Although Ctrl+Z would normally fix this problem, they are a bit more difficult to remove after compiling and might need to be removed manually. This is not a high priority but would make a good code cleanup.

**Comment by MattMoradi** [comment]
[https://stackoverflow.com/questions/20491653/how-do-i-delete-the-generated-function-from-accidentally-double-clicking-on-a-bu](url)

**Comment by hudson1740** [comment]
All empty on-click methods have been removed
