### ISSUE TITLE
Restart Fails When Text Is Present In The RichTextBox

### ISSUE THREAD

**Issue by MattMoradi** [Brett-Tech-Networking/Moradi-Notepad#54]
If text is inserted in the textbox and the restart button is selected, the application does not restart as the thread appears to be terminated by an `Enviroment.Exit(0)` reference on the save dialog.

**Comment by hudson1740** [comment]
fixed by replacing Enviorment(0); with Enviorment(1);

**Comment by hudson1740** [comment]
changing Enviorment(1); to Application.ExitThread(); seems to correct  this
