### ISSUE TITLE
Unhandled ArgumentException

### ISSUE THREAD

**Issue by MattMoradi** [Brett-Tech-Networking/Moradi-Notepad#6]
If a user attempts to decrease the font size to a degree that is out of range to the .NET SelectionFont size class-lib, an unhandled ArgumentException is thrown. In order to handle this exception, I would embed this function in a try-catch statement and execute a MessageBox in the catch block displaying an exception message that a standard human can understand telling them not to do that font shrinking trash no more. That should solve the error. 
![argumentexception_unhandled](https://user-images.githubusercontent.com/14935352/28553877-fa51c044-70aa-11e7-9898-e21d4275c320.PNG)

**Comment by MattMoradi** [comment]
I have already fixed this error and will release it in my next commit. You can disregard this and I shall close the issue later. :D

**Comment by MattMoradi** [comment]
When I was fixing the shrink exception, a funny thing happened. It caused a growth exception for the increase button...lol. I have no idea why but I fixed them both. These exception handling bug fixes will be released in my next patch commit.

**Comment by hudson1740** [comment]
awesome thank you for your repairs
