### ISSUE TITLE
Remove "Start Typing Here" On Mouse Click

### ISSUE THREAD

**Issue by MattMoradi** [Brett-Tech-Networking/Moradi-Notepad#7]
Not mandatory. Might need to call another .NET Function in order to handle such a click event. Just a suggestion enhancement.
![start_typing_here](https://user-images.githubusercontent.com/14935352/28554308-99be0af0-70ad-11e7-849e-76e6ac49e357.PNG)

**Comment by hudson1740** [comment]
if you have not already i will add the remove on click or remove text i like the text being there to show the theme colors however adding a remove text on mouse click would cause data lose if say i type a two paragraph story and click anywhere on the page boom all gone hmm
