### ISSUE TITLE
Saving Color (Background, Forcolor)

### ISSUE THREAD

**Issue by hudson1740** [Brett-Tech-Networking/Moradi-Notepad#9]
lets make our own text file extension to save color, and background color

**Comment by hudson1740** [comment]
Maybe as a temp solution we can save with
.RTF

**Comment by MattMoradi** [comment]
We could give that a try until we implement our own custom extension. However, make sure to also keep our existing file extensions. Don't remove them.

**Comment by MattMoradi** [comment]
Also make sure when adding features to the save function that you add it to all the save functions, seeing as we have multiple. Eventually we may want to implement the save function into its own class, but that's a problem for our future selves.

**Comment by hudson1740** [comment]
this issue has been fixed with new updated code that saves exact format & color Etc... no issues
